matrix:
  NAME:
    - lev-api
  MAJOR:
    - 0
  MINOR:
    - 0
  PATCH:
    - 8
  DOCKER_USERNAME:
    - lev-ci
  DOCKER_REPO:
    - docker.digital.homeoffice.gov.uk
pipeline:
  test_pr:
    image: quay.io/ukhomeofficedigital/lev-ci
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - make test
    when:
      event: pull_request
  docker-build-and-push:
    image: ukhomeoffice/drone-docker
    secrets: [ docker_password ]
    username: '${DOCKER_USERNAME}'
    repo: '${DOCKER_REPO}/${NAME}'
    registry: '${DOCKER_REPO}'
    tags:
      - '${MAJOR}.${MINOR}.${PATCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}'
      - '${MAJOR}.${MINOR}.${PATCH}'
      - '${MAJOR}.${MINOR}'
      - '${MAJOR}'
      - 'latest'
    when:
      event: push
      branch: master
  deploy_image:
    image: quay.io/ukhomeofficedigital/lev-ci
    secrets:
      - KUBE_SERVER
      - KUBE_NAMESPACE
      - KUBE_TOKEN
      - KUBE_DEPLOYMENT
      - KUBE_CONTAINER
      - USERNAME
      - PASSWORD
      - CLIENT_ID
      - CLIENT_SECRET
      - OIDC_URL
      - TEST_URL
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - TAG=${MAJOR}.${MINOR}.${PATCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}
    commands:
      - kubectl="kubectl --insecure-skip-tls-verify --server=$${KUBE_SERVER} --namespace=$${KUBE_NAMESPACE} --token=$${KUBE_TOKEN}"
      - $${kubectl} scale deployment "$${KUBE_DEPLOYMENT}" --replicas 2
      - $${kubectl} set image "deployment/$${KUBE_DEPLOYMENT}" "$${KUBE_CONTAINER}=${DOCKER_REPO}/${NAME}:$${TAG}"
      - $${kubectl} rollout status "deployment/$${KUBE_DEPLOYMENT}"
      - $${kubectl} scale deployment "$${KUBE_DEPLOYMENT}" --replicas 1
      - docker run --env "USERNAME=$${USERNAME}" --env "PASSWORD=$${PASSWORD}" --env "CLIENT_ID=$${CLIENT_ID}" --env "CLIENT_SECRET=$${CLIENT_SECRET}" --env "OIDC_URL=$${OIDC_URL}" --env "TEST_URL=$${TEST_URL}" quay.io/ukhomeofficedigital/lev-api-test:v${MAJOR}.${MINOR}
    when:
      branch: master
      event: push
  notify_slack_success:
    image: plugins/slack:1.0
    secrets:
      - SLACK_WEBHOOK
    channel: general
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      *Deployed {{repo.name}} to Dev-UK* - <{{build.link}}|#{{build.number}}>
    when:
      branch: master
      event: push
      status: success
  notify_slack_failure:
    image: plugins/slack
    secrets:
      - SLACK_WEBHOOK
    channel: alerts
    username: Drone
    icon_url: http://readme.drone.io/0.5/logo_dark.svg
    icon.url: http://readme.drone.io/0.5/logo_dark.svg
    template: >
      *Failed to deploy {{repo.name}} to Dev-UK*

      Author: {{build.author}}

      Duration: {{since job.started}}
      Job: <{{build.link}}|#{{build.number}}>

      Commit: {{build.commit}}
    when:
      branch: master
      event: push
      status: failure
